title: "Handwritten Digit Classification (MNIST)"
author: 
  - Dinesh Umasankar
date: \today
subject: "Machine Learning"
keywords: [MNIST, Handwritten Digit Classification, Digit Classification]
papersize: a4
lang: "en"
bibliography: references.bib
titlepage: true
titlepage-rule-color: "360049"
titlepage-rule-height: 0
titlepage-background: "assets/background.pdf"
link-citations: true
colorlinks: true
header-includes:
- |
  ```{=latex}
  \usepackage{tcolorbox}

  \newtcolorbox{info-box}{colback=cyan!5!white,arc=0pt,outer arc=0pt,colframe=cyan!60!black}
  \newtcolorbox{warning-box}{colback=orange!5!white,arc=0pt,outer arc=0pt,colframe=orange!80!black}
  \newtcolorbox{error-box}{colback=red!5!white,arc=0pt,outer arc=0pt,colframe=red!75!black}
  ```
pandoc-latex-environment:
  tcolorbox: [box]
  info-box: [info]
  warning-box: [warning]
  error-box: [error]
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl